### PR TITLE
Use member.toJSON in PropertyList.toJSON

### PR DESCRIPTION
**Pull request by kamalaknn**

### CODE REVIEW

**Comment by kamalaknn** [comment]
@shamasis, this uses `member.toJSON()` if it exists.

**Comment by czardoz** [comment]
@shamasis Nope, I can't see any, infinite recursion is not possible, because this only changes the PropertyList's `.toJSON()`.

**Comment by czardoz** [comment]
@kamalaknn Also, I've added you to repository collaborators, so you can just create branches here, instead of forking :)

**Comment by kamalaknn** [comment]
@czardoz Okay 👍

**Pull request merged**
