### PR TITLE
Ignore dots within variables on host

### PR DESCRIPTION
**Pull request by vegetableman**
This fixes the issue: https://github.com/postmanlabs/postman-app-support/issues/2629

### CODE REVIEW

**Comment by vegetableman** [comment]
@shamasis ^

**Comment by shamasis** [comment]
@vegetableman can you add a test for recursive variables? {{an.d-{{ano.ther}}}}

**Comment by vegetableman** [comment]
@czardoz Added more tests.
@shamasis Are we supporting nested variables? don't think a regex could take care of that case. Also, Ideally, the url class shouldn't care about variable resolution. Let me know if there's a better way of doing this fix.

**Comment by czardoz** [comment]
@vegetableman, the URL class is _not_ doing variable resolution, it's doing parsing of URLs containing variables. What @shamasis means is, your regex should ensure that any nested variables are preserved after parsing, meaning it should only consider the outermost `{{`

**Comment by vegetableman** [comment]
@czardoz I meant, is there any way we could do the domain split on the resolved values instead of the raw url itself?

**Comment by czardoz** [comment]
No, we're not trying to resolve anything here, just parsing the domain from the URL. There's no other way to do it :)

**Comment by vegetableman** [comment]
Updated. Couldn't find a place for `Splitter` other than `superstring` (it's not being used for the value though). Let me know if I should move it or refactor it.

**Comment by vegetableman** [comment]
@czardoz @shamasis Simplified the logic to do join after split.

**Comment by vegetableman** [comment]
@czardoz @shamasis Brought it back to it's original glory :/

**Comment by SamvelRaja** [comment]
Fixes the issue.
https://github.com/postmanlabs/postman-app-support/issues/2620

**Pull request merged**
