### PR TITLE
Added resolution correctness check for slashed variable names

### PR DESCRIPTION
**Pull request by kunagpal**
Both forward and backward slashes have been tested for, Appveyor settings need to be updated to allow builds to work correctly again.

### CODE REVIEW

**Comment by shamasis** [comment]
A bit more context please?

**Comment by kunagpal** [comment]
@shamasis https://github.com/postmanlabs/newman/issues/365

**Comment by shamasis** [comment]
So is the original issue not reproducible? Or fixed in prior PRs? I see only tests added.

**Comment by kunagpal** [comment]
This was fixed in postman-collection earlier, tests are being added.

**Pull request merged**
